### PR TITLE
feat: Update `Logger::enabled`

### PR DESCRIPTION
**Pull request by apepkuss**
Major change:

- Update `Logger::enabled` method

### CODE REVIEW

**Comment by juntyr** [comment]
Thanks @apepkuss for this PR! Do you want a release with this change to be published immediately or are you intending to submit several smaller changes?

**Comment by apepkuss** [comment]
@juntyr Thanks for the review. For now, this is the only PR, and not necessary to publish a new release for it. Thanks :)

BTW, we're reviwing a [PR](https://github.com/WasmEdge/WasmEdge/pull/3416) in WasmEdge repo, which supports log file as a target. Do you have any plan to support the file target in `wasi-logger`? Actually, I am not sure if `wasi-logger` supports switching target. If it does, could you please give a short example in this project? Thanks again!

**Comment by juntyr** [comment]
The `wasi-logger` crate only handles the WASM-guest side and has no idea what you end up doing with the log messages. On the host side, where the `wasi:logging/logging` interface is implemented, you can then decide what to do with these messages, e.g. feed them back into a Rust logger, write them to stdout/err or to a file, etc, but all of these are out of scope for this crate (since providing host implementations is still runtime-specific).

It seems that the PR you mention uses the "context" field to communicate the eventual target of the message. This crate extracts this context from the `target` expression in the log macros (e.g. [`log::log!`](https://docs.rs/log/latest/log/macro.log.html)), so you could e.g. write

```rust
log::log!(target: "stdout", log::Level::Info, "my message to stdout");
```

to set the message context to `"stdout"` which the host implementation could then pick up on to forward the message to stdout.

**Comment by apepkuss** [comment]
Thank you so much for the explanation!

**Comment by juntyr** [comment]
I've now released https://github.com/juntyr/wasi-logger/releases/tag/0.1.2

**Pull request merged**
